---
- name: Install Nginx on Public_Server
  apt:
    name: nginx
    state: present

- name: Configure Nginx reverse proxy
  template:
    src: main.j2
    dest: /etc/nginx/sites-available/reverse_proxy.conf
  notify: Restart Nginx

- name: Enable reverse proxy configuration
  file:
    src: /etc/nginx/sites-available/reverse_proxy.conf
    dest: /etc/nginx/sites-enabled/reverse_proxy.conf
    state: link
  notify: Restart Nginx