---
- name: Install Nginx on Public_Server
  apt:
    name: nginx
    state: present

- name: Configure Nginx reverse proxy
  template:
    src: main.j2
    dest: "{{ available_dir }}"
  notify: Restart Nginx

- name: Enable reverse proxy configuration
  file:
    src: "{{ available_dir }}"
    dest: "{{ enabled_dir }}"
    state: link
  notify: Restart Nginx