- name: Install common packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ common_packages }}"

- name: Download pyenv script
  ansible.builtin.get_url:
    dest: /tmp/pyenv.sh
    url: https://pyenv.run
    mode: "0555"

- name: Execute pyenv install script
  shell:
    cmd: /tmp/pyenv.sh
    creates: "{{ home_dir }}/.pyenv"

- name: Clone the Django project repository
  ansible.builtin.git:
    repo: https://github.com/UjjwalBudha/simple-django-project.git
    dest: /root/simple-django-project
    force: yes
    

- name: Check if Python 3.7.2 is already installed
  shell: "{{ pyenv_dir }} versions | grep -q '3.7.2'"
  register: python_3_7_2_installed
  changed_when: false
  ignore_errors: true

- name: Install Python 3.7.2 using pyenv
  ansible.builtin.shell:
    cmd: |
      {{ pyenv_dir }} install 3.7.2
  when: python_3_7_2_installed.rc != 0

- name: Ensure the directory exists
  file:
    path: /root/test001
    state: directory
    mode: '0755'

- name: Install pyenv locally for specific directory
  ansible.builtin.shell:
    chdir: /root/test001
    cmd: |
      {{ pyenv_dir }} local 3.7.2

- name: Import .sql file 
  shell: mysql -uroot < /root/simple-django-project/world.sql 


- name: Ensure pyenv initialization in .bashrc
  blockinfile:
    path: ~/.bashrc
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init --path)"
      eval "$(pyenv init -)"

- name: Remove existing virtual environment
  file:
    path: /root/.pyenv/versions/3.7.2/envs/test001
    state: absent

- name: Remove existing virtual environment
  file:
    path: /root/.pyenv/versions/test001
    state: absent


- name: Create virtual environment with pyenv
  shell: /root/.pyenv/bin/pyenv virtualenv 3.7.2 test001
  

- name: Activate pyenv venv and change directory to simple-django-project
  shell: >
    . ~/.bashrc && pyenv activate test001 && cd /root/simple-django-project

- name: Upgrade pip version to latest
  shell: >
    . ~/.bashrc && pyenv activate test001 && pip install --upgrade pip
  args:
    chdir: /root/simple-django-project

- name: Install dependencies from requirements.txt
  shell: >
    . ~/.bashrc && pyenv activate test001 && pip install -r requirements.txt
  args:
    chdir: /root/simple-django-project

- name: Run Django migrations
  shell: >
    . ~/.bashrc && pyenv activate test001 && python manage.py makemigrations && python manage.py migrate
  args:
    chdir: /root/simple-django-project

- name: Rebuild Django search index
  shell: >
    . ~/.bashrc && pyenv activate test001 && python manage.py rebuild_index
  args:
    chdir: /root/simple-django-project

- name: Run Django development server
  shell: >
    . ~/.bashrc && pyenv activate test001 && python manage.py runserver 0:8001 &
  args:
    chdir: /root/simple-django-project