---
plugin: aws_ec2
regions:
  - us-east-1
filters:
  instance-state-name: running
  "tag:owner": ujwal.budha
hostnames:
  - instance-id

groups:
  public_server: "'public' in tags.Name"
  private_server: "'private' in tags.Name"