---
# - hosts: i-003db8f1004f8f52b
#   gather_facts: true
#   become: true
#   roles:
#     - django
#   vars:
#     ansible_connection: aws_ssm
#     ansible_aws_ssm_bucket_name: 8586-terraform-state 
#     ansible_aws_ssm_profile: default
#     ansible_aws_ssm_timeout: 300

- hosts: i-090b0d4c36dbcc597
  gather_facts: true
  become: true
  roles:
    - nginx
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: 8586-terraform-state 
    ansible_aws_ssm_profile: default
    ansible_aws_ssm_timeout: 300
    ansible_python_interpreter: /usr/bin/python3
