---
- hosts: public_server
  gather_facts: true
  become: true
  roles:
    - django
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: 8586-terraform-state 
    ansible_aws_ssm_profile: default
    ansible_aws_ssm_timeout: 300

- hosts: private_server
  gather_facts: true
  become: true
  roles:
    - nginx
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: 8586-terraform-state 
    ansible_aws_ssm_profile: default
    ansible_aws_ssm_timeout: 300
    ansible_python_interpreter: /usr/bin/python3
